--
-- Roles
--


CREATE ROLE "FA_PAYMENT_INSTRUMENT_REMOTE_USER";
ALTER ROLE "FA_PAYMENT_INSTRUMENT_REMOTE_USER" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
ALTER USER "FA_PAYMENT_INSTRUMENT_REMOTE_USER" WITH PASSWORD '${faPaymentInstrumentRemoteUserPassword}';

CREATE ROLE "FA_USER";
ALTER ROLE "FA_USER" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
ALTER USER "FA_USER" WITH PASSWORD '${faUserPassword}';

CREATE ROLE "RTD_USER";
ALTER ROLE "RTD_USER" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
ALTER USER "RTD_USER" WITH PASSWORD '${rtdUserPassword}';

CREATE ROLE "tkm_acquirer_manager";
ALTER ROLE "tkm_acquirer_manager" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
ALTER USER "tkm_acquirer_manager" WITH PASSWORD '${tkmAcquirerManagerUserPassword}';

--
-- Role memberships
--

GRANT "RTD_USER" TO ddsadmin GRANTED BY ddsadmin;

-- Database creation
--

GRANT ALL ON DATABASE fa TO "FA_USER";
GRANT CONNECT ON DATABASE fa TO "FA_PAYMENT_INSTRUMENT_REMOTE_USER";
GRANT CONNECT ON DATABASE rtd TO "RTD_USER";