--
-- Roles
--

CREATE ROLE "FA_USER";
ALTER ROLE "FA_USER" WITH INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
ALTER USER "FA_USER" WITH PASSWORD '${faUserPassword}';

CREATE ROLE "RTD_USER";
ALTER ROLE "RTD_USER" WITH INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
ALTER USER "RTD_USER" WITH PASSWORD '${rtdUserPassword}';

--
-- Role memberships
--

GRANT "FA_USER" TO "${adminUser}" GRANTED BY "${adminUser}";
GRANT "RTD_USER" TO "${adminUser}" GRANTED BY "${adminUser}";

GRANT ALL ON DATABASE fa TO "FA_USER";
GRANT ALL ON DATABASE rtd TO "RTD_USER";

