DROP INDEX bpd_payment_instrument.bpd_payment_instrument_par_s_idx;
DROP INDEX bpd_winning_transaction.bpd_winning_transaction_enabled_b_idx;
DROP INDEX bpd_winning_transaction.bpd_winning_transaction_hpan_s_fiscal_code_s_trx_timestamp__idx;
DROP INDEX bpd_winning_transaction.bpd_winning_transaction_hpan_s_fiscal_code_s_trx_timestamp_idx1;
DROP INDEX bpd_winning_transaction.bpd_winning_transaction_hpan_s_fiscal_code_s_trx_timestamp_idx2;
