apiVersion: v1
data:
  AWARD_PERIOD_REST_CLIENT_ACTIVES_CACHE_CRON: 0 0 0 * * ?
  LOG_LEVEL_BPD_AWARD_PERIOD: DEBUG
  POSTGRES_POOLSIZE: "2"
  POSTGRES_SCHEMA: bpd_award_period
  POSTGRES_SHOW_SQL: "true"
kind: ConfigMap
metadata:
  name: bpdmsawardperiod
  namespace: bpd
