apiVersion: v1
data:
  BPD_CITIZEN_HOST: bpdmscitizen
  BPD_MS_AWARD_PERIOD_HOST: bpdmsawardperiod
  BPD_MS_WINNING_TRANSACTION_HOST: bpdmswinningtransaction
  BPD_PAYMENT_INSTRUMENT_HOST: bpdmspaymentinstrument
  REST_CLIENT_SCHEMA: http
kind: ConfigMap
metadata:
  name: rest-client
  namespace: bpd
