CREATE ROLE "MONITORING_PDND_USER";
ALTER ROLE "MONITORING_PDND_USER" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
ALTER USER "MONITORING_PDND_USER" WITH PASSWORD '${monitoringPdndUserPassword}';
GRANT CONNECT ON DATABASE bpd TO "MONITORING_PDND_USER";
GRANT CREATE ON DATABASE fa TO "MONITORING_PDND_USER";
GRANT CONNECT ON DATABASE postgres TO "MONITORING_PDND_USER";
GRANT CONNECT ON DATABASE rtd TO "MONITORING_PDND_USER";
