parameters:
  - name: 'ENV'
    displayName: 'Environment to deploy'
    type: string
    values:
      - dev
      - uat
      - prod
    default: 'prod'
  - name: 'WORKING_DIR_APP'
    displayName: 'app domain working dir'
    type: string
    default: ''
  - name: 'WORKING_DIR_COMMON'
    displayName: 'common domain working dir'
    type: string
    default: ''
  - name: 'WORKING_DIR_SECRET'
    displayName: 'secret domain working dir'
    type: string
    default: ''
  - name: 'WORKING_DIR_MODULE'
    displayName: 'generic working dir'
    type: string
    default: ''
  - name: 'ENV_LOCATION'
    displayName: 'region of choice for this domain'
    type: string
    default: 'itn'
  - name: 'SC_PLAN_NAME'
    type: string
  - name: 'AKS_APISERVER_URL'
    type: string
    default: ''
  - name: 'AKS_AZURE_DEVOPS_SA_CACRT'
    type: string
    default: ''
  - name: 'AKS_AZURE_DEVOPS_SA_TOKEN'
    type: string
    default: ''
  - name: 'AKS_NAME'
    type: string
    default: ''
  - name: 'POOL_NAME'
    type: string
  - name: 'TIME_OUT'
    type: number
    default: 15

stages:
  - stage: ${{parameters.ENV}}
    displayName: 'Code review for ${{parameters.ENV}}'
    dependsOn: []
    condition: succeeded()
    pool:
      name: "${{parameters.POOL_NAME}}"
    jobs:
      - ${{ if ne(parameters.WORKING_DIR_SECRET, '') }}:
        - job: tfplan_secret
          strategy:
           parallel: 1
          timeoutInMinutes: ${{parameters.TIME_OUT}}
          steps:
           - checkout: self
           # 1. Install terraform
           - template: templates/terraform-setup/template.yaml@terraform
           - template: templates/terraform-summarize/template.yaml@terraform
           # 2. Run terraform plan core
           - template: templates/terraform-plan/template.yaml@terraform
             parameters:
               TF_ENVIRONMENT_FOLDER: "${{parameters.ENV_LOCATION}}-${{lower(parameters.ENV)}}"
               WORKINGDIR: ${{ parameters.WORKING_DIR_SECRET }}
               AZURE_SERVICE_CONNECTION_NAME: "${{parameters.SC_PLAN_NAME}}"
               TF_SUMMARIZE: true
      - ${{ if ne(parameters.WORKING_DIR_COMMON, '') }}:
        - job: tfplan_common
          strategy:
            parallel: 1
          timeoutInMinutes: ${{parameters.TIME_OUT}}
          steps:
            - checkout: self
            # 1. Install terraform
            - template: templates/terraform-setup/template.yaml@terraform
            - template: templates/terraform-summarize/template.yaml@terraform
            # 2. Run terraform plan core
            - template: templates/terraform-plan/template.yaml@terraform
              parameters:
                TF_ENVIRONMENT_FOLDER: "${{parameters.ENV_LOCATION}}-${{lower(parameters.ENV)}}"
                WORKINGDIR: ${{ parameters.WORKING_DIR_COMMON }}
                AZURE_SERVICE_CONNECTION_NAME: "${{parameters.SC_PLAN_NAME}}"
                TF_SUMMARIZE: true
                AKS_NAME: ${{ parameters.AKS_NAME }}
                AKS_API_SERVER_URL: ${{ parameters.AKS_APISERVER_URL }}
                AKS_AZURE_DEVOPS_SA_CA_CRT: ${{ parameters.AKS_AZURE_DEVOPS_SA_CACRT }}
                AKS_AZURE_DEVOPS_SA_TOKEN: ${{ parameters.AKS_AZURE_DEVOPS_SA_TOKEN }}
      - ${{ if ne(parameters.WORKING_DIR_APP, '') }}:
        - job: tfplan_app
          strategy:
            parallel: 1
          timeoutInMinutes: ${{parameters.TIME_OUT}}
          steps:
            - checkout: self
            # 1. Install terraform
            - template: templates/terraform-setup/template.yaml@terraform
            - template: templates/terraform-summarize/template.yaml@terraform
            # 2. Run terraform plan core
            - template: templates/terraform-plan/template.yaml@terraform
              parameters:
                TF_ENVIRONMENT_FOLDER: "${{parameters.ENV_LOCATION}}-${{lower(parameters.ENV)}}"
                WORKINGDIR: ${{ parameters.WORKING_DIR_APP }}
                AZURE_SERVICE_CONNECTION_NAME: "${{parameters.SC_PLAN_NAME}}"
                TF_SUMMARIZE: true
                AKS_NAME: ${{ parameters.AKS_NAME }}
                AKS_API_SERVER_URL: ${{ parameters.AKS_APISERVER_URL }}
                AKS_AZURE_DEVOPS_SA_CA_CRT: ${{ parameters.AKS_AZURE_DEVOPS_SA_CACRT }}
                AKS_AZURE_DEVOPS_SA_TOKEN: ${{ parameters.AKS_AZURE_DEVOPS_SA_TOKEN }}
      - ${{ if ne(parameters.WORKING_DIR_MODULE, '') }}:
        - job: tfplan_module
          strategy:
            parallel: 1
          timeoutInMinutes: ${{parameters.TIME_OUT}}
          steps:
            - checkout: self
            # 1. Install terraform
            - template: templates/terraform-setup/template.yaml@terraform
            - template: templates/terraform-summarize/template.yaml@terraform
            # 2. Run terraform plan core
            - template: templates/terraform-plan/template.yaml@terraform
              parameters:
                TF_ENVIRONMENT_FOLDER: "${{parameters.ENV_LOCATION}}-${{lower(parameters.ENV)}}"
                WORKINGDIR: ${{ parameters.WORKING_DIR_MODULE }}
                AZURE_SERVICE_CONNECTION_NAME: "${{parameters.SC_PLAN_NAME}}"
                TF_SUMMARIZE: true

