# only manual
trigger: none
pr: none

parameters:
  - name: 'DEV'
    displayName: 'Run on DEV environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'UAT'
    displayName: 'Run on UAT environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'PROD'
    displayName: 'Run on PROD environment'
    type: boolean
    default: True
    values:
      - False
      - True

variables:
  TIME_OUT: 10
  # working dir
  WORKING_DIR: 'src/core'
  DOMAIN_NAME: core
  #APPLY
  DEV_APPLY_AZURE_SERVICE_CONNECTION_NAME: ${{variables.dev_apply_service_connection_name}}
  UAT_APPLY_AZURE_SERVICE_CONNECTION_NAME: ${{variables.uat_apply_service_connection_name}}
  PROD_APPLY_AZURE_SERVICE_CONNECTION_NAME: ${{variables.prod_apply_service_connection_name}}
  #PLAN
  DEV_PLAN_AZURE_SERVICE_CONNECTION_NAME: ${{variables.dev_plan_service_connection_name}}
  UAT_PLAN_AZURE_SERVICE_CONNECTION_NAME: ${{variables.uat_plan_service_connection_name}}
  PROD_PLAN_AZURE_SERVICE_CONNECTION_NAME: ${{variables.prod_plan_service_connection_name}}

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v5.0.1
      endpoint: 'io-azure-devops-github-ro'

stages:
#DEV
  - ${{ if eq(parameters['DEV'], true) }}:
    - template: templates/terraform-plan-apply/template.yaml@terraform
      parameters:
        FULL_DOMAIN_NAME: "${{variables.DOMAIN_NAME}}_common"
        TF_ENVIRONMENT_FOLDER: "dev"
        ENVIRONMENT: "DEV"
        AZURE_DEVOPS_POOL_AGENT_NAME: "cstar-dev-linux-infra"
        WORKINGDIR: ${{ variables.WORKING_DIR }}
        AZURE_SERVICE_CONNECTION_PLAN_NAME: ${{variables.DEV_PLAN_AZURE_SERVICE_CONNECTION_NAME}}
        AZURE_SERVICE_CONNECTION_APPLY_NAME: ${{variables.DEV_APPLY_AZURE_SERVICE_CONNECTION_NAME}}
#UAT
  - ${{ if eq(parameters['UAT'], true) }}:
    - template: templates/terraform-plan-apply/template.yaml@terraform
      parameters:
        FULL_DOMAIN_NAME: "${{variables.DOMAIN_NAME}}_common"
        TF_ENVIRONMENT_FOLDER: "uat"
        ENVIRONMENT: "UAT"
        AZURE_DEVOPS_POOL_AGENT_NAME: "cstar-uat-linux-infra"
        WORKINGDIR: ${{ variables.WORKING_DIR }}
        AZURE_SERVICE_CONNECTION_PLAN_NAME: ${{variables.UAT_PLAN_AZURE_SERVICE_CONNECTION_NAME}}
        AZURE_SERVICE_CONNECTION_APPLY_NAME: ${{variables.UAT_APPLY_AZURE_SERVICE_CONNECTION_NAME}}
#PROD
  - ${{ if eq(parameters['PROD'], true) }}:
    - template: templates/terraform-plan-apply/template.yaml@terraform
      parameters:
        FULL_DOMAIN_NAME: "${{variables.DOMAIN_NAME}}_common"
        TF_ENVIRONMENT_FOLDER: "prod"
        ENVIRONMENT: "PROD"
        AZURE_DEVOPS_POOL_AGENT_NAME: "cstar-prod-linux-infra"
        WORKINGDIR: ${{ variables.WORKING_DIR }}
        AZURE_SERVICE_CONNECTION_PLAN_NAME: ${{variables.PROD_PLAN_AZURE_SERVICE_CONNECTION_NAME}}
        AZURE_SERVICE_CONNECTION_APPLY_NAME: ${{variables.PROD_APPLY_AZURE_SERVICE_CONNECTION_NAME}}
