# Automatically triggered on PR
# Only triggers on branches
pr:
  autoCancel: true
  branches:
    exclude:
     - '*'

trigger:
  branches:
    exclude:
      - master
  paths:
    include:
      - 'src/*'

parameters:
  - name: 'SUBSCRIPTION'
    displayName: 'Azure subscription hosting the infrastructure built with terraform'
    type: string
    default: DEV-CSTAR-SERVICE-CONN
    values:
      - PROD-CSTAR-SERVICE-CONN
      - UAT-CSTAR-SERVICE-CONN
      - DEV-CSTAR-SERVICE-CONN
pool:
  vmImage: 'ubuntu-latest'


resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: split-terraform-and-terragrunt-template
      endpoint: 'cstar-projects'

jobs:
  - job: terraform_plan
    steps:
      # 1. Install terraform and terragrunt
      - template: templates/terraform-setup/template.yaml@terraform
      # 4. Run terragrunt plan
      - task: AzureCLI@2
        displayName: Terraform init 
        inputs:
          azureSubscription: '${{ parameters.SUBSCRIPTION }}'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          failOnStandardError: true
          workingDirectory: src
          inlineScript: |
            RED='\033[0;31m'
            NC='\033[0m' # No Color

            export ARM_CLIENT_ID=$env:servicePrincipalId
            export ARM_CLIENT_SECRET=$env:servicePrincipalKey
            export ARM_SUBSCRIPTION_ID=`az account show --query id --output tsv`
            export ARM_TENANT_ID=$env:tenantId

            echo ${ARM_TENANT_ID}
            
            ./terraform.sh init dev
            terraform validate

            