# Automatically triggered on PR
# Only triggers on branches
pr:
  autoCancel: true
  branches:
    exclude:
     - '*'

trigger:
  branches:
    exclude:
      - master
  paths:
    include:
      - 'src/*'
      - '.devops/*'
    exclude:
      - 'src/k8s/*'

parameters:
  - name: 'SUBSCRIPTION'
    displayName: 'Azure subscription hosting the infrastructure built with terraform'
    type: string
    default: DEV-CSTAR-SERVICE-CONN
    values:
      - PROD-CSTAR-SERVICE-CONN
      - UAT-CSTAR-SERVICE-CONN
      - DEV-CSTAR-SERVICE-CONN
pool:
  vmImage: 'ubuntu-20.04'


resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: terrarorm-plan-template
      endpoint: 'io-azure-devops-github-ro'

stages:
  - stage: install
    jobs:
      - job: terraform_install
        steps:
          # 1. Install terraform and terragrunt
          - template: templates/terraform-setup/template.yaml@terraform
  - stage: plan_dev    
    jobs:
      - job: terraform_plan
        steps:
          # 2. Run terragrunt plan
          - template: templates/terraform-plan/template.yaml@terraform
            parameters:
              SUBSCRIPTION: 'DEV-CSTAR-SERVICE-CONN'
              ENVIRONMENT: 'dev'
  - stage: apply_dev    
    jobs:
      - deployment: terraform_apply
        displayName: "terraform apply"
        continueOnError: false
        environment: "Verify"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                # 3. Run terraform apply
                - template: templates/terraform-apply/template.yaml@terraform
                  parameters:
                    SUBSCRIPTION: 'DEV-CSTAR-SERVICE-CONN'
                    ENVIRONMENT: 'dev'
  - stage: plan_uat 
    jobs:
      - job: terraform_plan
        steps:
          # 4. Run terragrunt plan
          - template: templates/terraform-plan/template.yaml@terraform
            parameters:
              SUBSCRIPTION: 'UAT-CSTAR-SERVICE-CONN'
              ENVIRONMENT: 'uat'
  - stage: apply_uat    
    jobs:
      - deployment: terraform_apply
        displayName: "terraform apply"
        continueOnError: false
        environment: "Verify"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                # 5. Run terraform apply
                - template: templates/terraform-apply/template.yaml@terraform
                  parameters:
                    SUBSCRIPTION: 'UAT-CSTAR-SERVICE-CONN'
                    ENVIRONMENT: 'uat'
  - stage: plan_prod 
    jobs:
      - job: terraform_plan
        steps:
          # 6. Run terragrunt plan
          - template: templates/terraform-plan/template.yaml@terraform
            parameters:
              SUBSCRIPTION: 'PROD-CSTAR-SERVICE-CONN'
              ENVIRONMENT: 'prod'
  - stage: apply_prod
    jobs:
      - deployment: terraform_apply
        displayName: "terraform apply"
        continueOnError: false
        environment: "Verify"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                # 7. Run terraform apply
                - template: templates/terraform-apply/template.yaml@terraform
                  parameters:
                    SUBSCRIPTION: 'PROD-CSTAR-SERVICE-CONN'
                    ENVIRONMENT: 'prod'