# Automatically triggered on PR
# Only triggers on branches
pr:
  autoCancel: true
  branches:
    exclude:
     - '*'

trigger:
  branches:
    exclude:
      - master
  paths:
    include:
      - 'src/*'
      - '.devops/*'
    exclude:
      - 'src/k8s/*'

parameters:
  - name: 'SUBSCRIPTION'
    displayName: 'Azure subscription hosting the infrastructure built with terraform'
    type: string
    default: DEV-CSTAR-SERVICE-CONN
    values:
      - PROD-CSTAR-SERVICE-CONN
      - UAT-CSTAR-SERVICE-CONN
      - DEV-CSTAR-SERVICE-CONN
pool:
  vmImage: 'ubuntu-20.04'


resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v16
      endpoint: 'io-azure-devops-github-ro'

jobs:
  - job: terraform_plan
    steps:
      # 1. Install terraform and terragrunt
      - template: templates/terraform-setup/template.yaml@terraform
      # 2. Run terragrunt plan
      - task: AzureCLI@2
        displayName: Terraform plan
        inputs:
          azureSubscription: '${{ parameters.SUBSCRIPTION }}'
          addSpnToEnvironment: true
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          failOnStandardError: true
          workingDirectory: src
          inlineScript: |
            RED='\033[0;31m'
            NC='\033[0m' # No Color

            echo "Start pipeline"

            export ARM_CLIENT_ID=$servicePrincipalId
            export ARM_CLIENT_SECRET=$servicePrincipalKey
            export ARM_SUBSCRIPTION_ID=`az account show --query id --output tsv`
            export ARM_TENANT_ID=`az account show --query tenantId --output tsv`

            ./terraform.sh init dev
            terraform validate
            ./terraform.sh plan dev
      # 3. manual validation
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # task times out in 1 day
        inputs:
          notifyUsers: |
            io-operations@pagopa.it
          instructions: 'Please validate the plan to apply.'
          onTimeout: 'resume'
      - task: AzureCLI@2
        displayName: Terraform apply
        inputs:
          azureSubscription: '${{ parameters.SUBSCRIPTION }}'
          addSpnToEnvironment: true
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          failOnStandardError: true
          workingDirectory: src
          inlineScript: |
            RED='\033[0;31m'
            NC='\033[0m' # No Color

            echo "Start pipeline"

            ./terraform.sh apply dev -auto-approve
            