# Automatically triggered on PR
# Only triggers on branches
trigger:
  paths:
    include:
      - 'src/*'
      - '.devops/*'
    exclude:
      - 'src/k8s/*'
pr:
  branches:
    include:
      - main
      - release*

pool:
  vmImage: 'ubuntu-20.04'

resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v17
      endpoint: 'io-azure-devops-github-ro'

variables:
  isToDeploy: $[and(ne(variables['Build.Reason'], 'PullRequest'), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix')))]
  
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/release-dev') }}:
    environment: 'dev'
  ${{ elseif or(startsWith(variables['Build.SourceBranch'], 'refs/heads/release-uat'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix')) }}:
    environment: 'uat'
  ${{ elseif or(eq(variables['Build.SourceBranch'], 'refs/heads/master'),eq(variables['Build.SourceBranch'], 'refs/heads/main')) }}:
    environment: 'prod'
  ${{ else }}:
    environment: 'dev'
    
stages:
  - stage: install
    jobs:
      - job: terraform_install
        steps:
          # 1. Install terraform and terragrunt
          - template: templates/terraform-setup/template.yaml@terraform
  - stage: plan  
    jobs:
      - job: terraform_plan
        steps:
          # 2. Run terragrunt plan
          - template: templates/terraform-plan/template.yaml@terraform
            parameters:
              SUBSCRIPTION: 'DEV-CSTAR-SERVICE-CONN'
              ENVIRONMENT: 'dev'
  - stage: apply
    condition: and(succeeded(), eq(variables.isToDeploy, true))
    jobs:
      - deployment: terraform_apply
        displayName: "terraform apply"
        continueOnError: false
        environment: "Verify"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                # 3. Run terraform apply
                - template: templates/terraform-apply/template.yaml@terraform
                  parameters:
                    SUBSCRIPTION: '${{ upper(variables.environment)}}-CSTAR-SERVICE-CONN'
                    ENVIRONMENT: ${{ variables.environment }}
