# only manual
trigger: none
pr: none

parameters:
  - name: 'DEV'
    displayName: 'Run on DEV environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'UAT'
    displayName: 'Run on UAT environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'PROD'
    displayName: 'Run on PROD environment'
    type: boolean
    default: True
    values:
      - False
      - True

variables:
  TIME_OUT: 10
  #dev
  DEV01_AKS_APISERVER_URL: '$(TF_DEV01_AKS_APISERVER_URL)'
  DEV01_AKS_AZURE_DEVOPS_SA_CACRT: '$(TF_DEV01_AKS_AZURE_DEVOPS_SA_CACRT)'
  DEV01_AKS_AZURE_DEVOPS_SA_TOKEN: '$(TF_DEV01_AKS_AZURE_DEVOPS_SA_TOKEN)'
  AKS_DEV_NAME: '$(TF_AKS_DEV_NAME)'
  #uat
  UAT01_AKS_APISERVER_URL: '$(TF_UAT01_AKS_APISERVER_URL)'
  UAT01_AKS_AZURE_DEVOPS_SA_CACRT: '$(TF_UAT01_AKS_AZURE_DEVOPS_SA_CACRT)'
  UAT01_AKS_AZURE_DEVOPS_SA_TOKEN: '$(TF_UAT01_AKS_AZURE_DEVOPS_SA_TOKEN)'
  AKS_UAT_NAME: '$(TF_AKS_UAT_NAME)'
  #prod
  PROD01_AKS_APISERVER_URL: '$(TF_PROD01_AKS_APISERVER_URL)'
  PROD01_AKS_AZURE_DEVOPS_SA_CACRT: '$(TF_PROD01_AKS_AZURE_DEVOPS_SA_CACRT)'
  PROD01_AKS_AZURE_DEVOPS_SA_TOKEN: '$(TF_PROD01_AKS_AZURE_DEVOPS_SA_TOKEN)'
  AKS_PROD_NAME: '$(TF_AKS_PROD_NAME)'
  # working dir
  WORKING_DIR_COMMON: 'src/domains/idpay-common'
  WORKING_DIR_APP: 'src/domains/idpay-app'
  DOMAIN_NAME: idpay

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v5.0.1
      endpoint: 'io-azure-devops-github-ro'

stages:
#DEV
  - ${{ if eq(parameters['DEV'], true) }}:
    - template: templates/terraform-plan-apply/template.yaml@terraform
      parameters:
        FULL_DOMAIN_NAME: "${{variables.DOMAIN_NAME}}_common"
        TF_ENVIRONMENT_FOLDER: "dev"
        ENVIRONMENT: "DEV"
        AZURE_DEVOPS_POOL_AGENT_NAME: "cstar-dev-linux-infra"
        WORKINGDIR: ${{ variables.WORKING_DIR_COMMON }}
        AZURE_SERVICE_CONNECTION_PLAN_NAME: CSTAR-DEV-PLAN-SERVICE-CONN
        AZURE_SERVICE_CONNECTION_APPLY_NAME: DEV-CSTAR-SERVICE-CONN
    - template: templates/terraform-plan-apply/template.yaml@terraform
      parameters:
        FULL_DOMAIN_NAME: "${{variables.DOMAIN_NAME}}_app"
        TF_ENVIRONMENT_FOLDER: "dev"
        ENVIRONMENT: "DEV"
        AZURE_DEVOPS_POOL_AGENT_NAME: "cstar-dev-linux-infra"
        WORKINGDIR:  ${{ variables.WORKING_DIR_APP }}
        AKS_NAME: ${{ variables.AKS_DEV_NAME }}
        AKS_API_SERVER_URL: ${{ variables.DEV01_AKS_APISERVER_URL }}
        AKS_AZURE_DEVOPS_SA_CA_CRT: ${{ variables.DEV01_AKS_AZURE_DEVOPS_SA_CACRT }}
        AKS_AZURE_DEVOPS_SA_TOKEN: ${{ variables.DEV01_AKS_AZURE_DEVOPS_SA_TOKEN }}
        AZURE_SERVICE_CONNECTION_PLAN_NAME: CSTAR-DEV-PLAN-SERVICE-CONN
        AZURE_SERVICE_CONNECTION_APPLY_NAME: DEV-CSTAR-SERVICE-CONN
#UAT
  - ${{ if eq(parameters['UAT'], true) }}:
    - template: templates/terraform-plan-apply/template.yaml@terraform
      parameters:
        FULL_DOMAIN_NAME: "${{variables.DOMAIN_NAME}}_common"
        TF_ENVIRONMENT_FOLDER: "uat"
        ENVIRONMENT: "UAT"
        AZURE_DEVOPS_POOL_AGENT_NAME: "cstar-uat-linux-infra"
        WORKINGDIR: ${{ variables.WORKING_DIR_COMMON }}
        AZURE_SERVICE_CONNECTION_PLAN_NAME: CSTAR-UAT-PLAN-SERVICE-CONN
        AZURE_SERVICE_CONNECTION_APPLY_NAME: UAT-CSTAR-SERVICE-CONN
    - template: templates/terraform-plan-apply/template.yaml@terraform
      parameters:
        FULL_DOMAIN_NAME: "${{variables.DOMAIN_NAME}}_app"
        TF_ENVIRONMENT_FOLDER: "uat"
        ENVIRONMENT: "UAT"
        AZURE_DEVOPS_POOL_AGENT_NAME: "cstar-uat-linux-infra"
        WORKINGDIR:  ${{ variables.WORKING_DIR_APP }}
        AKS_NAME: ${{ variables.AKS_UAT_NAME }}
        AKS_API_SERVER_URL: ${{ variables.UAT01_AKS_APISERVER_URL }}
        AKS_AZURE_DEVOPS_SA_CA_CRT: ${{ variables.UAT01_AKS_AZURE_DEVOPS_SA_CACRT }}
        AKS_AZURE_DEVOPS_SA_TOKEN: ${{ variables.UAT01_AKS_AZURE_DEVOPS_SA_TOKEN }}
        AZURE_SERVICE_CONNECTION_PLAN_NAME: CSTAR-UAT-PLAN-SERVICE-CONN
        AZURE_SERVICE_CONNECTION_APPLY_NAME: UAT-CSTAR-SERVICE-CONN
#PROD
  - ${{ if eq(parameters['PROD'], true) }}:
    - template: templates/terraform-plan-apply/template.yaml@terraform
      parameters:
        FULL_DOMAIN_NAME: "${{variables.DOMAIN_NAME}}_common"
        TF_ENVIRONMENT_FOLDER: "prod"
        ENVIRONMENT: "PROD"
        AZURE_DEVOPS_POOL_AGENT_NAME: "cstar-prod-linux-infra"
        WORKINGDIR: ${{ variables.WORKING_DIR_COMMON }}
        AZURE_SERVICE_CONNECTION_PLAN_NAME: CSTAR-PROD-PLAN-SERVICE-CONN
        AZURE_SERVICE_CONNECTION_APPLY_NAME: PROD-CSTAR-SERVICE-CONN
    - template: templates/terraform-plan-apply/template.yaml@terraform
      parameters:
        FULL_DOMAIN_NAME: "${{variables.DOMAIN_NAME}}_app"
        TF_ENVIRONMENT_FOLDER: "prod"
        ENVIRONMENT: "PROD"
        AZURE_DEVOPS_POOL_AGENT_NAME: "cstar-prod-linux-infra"
        WORKINGDIR:  ${{ variables.WORKING_DIR_APP }}
        AKS_NAME: ${{ variables.AKS_PROD_NAME }}
        AKS_API_SERVER_URL: ${{ variables.PROD01_AKS_APISERVER_URL }}
        AKS_AZURE_DEVOPS_SA_CA_CRT: ${{ variables.PROD01_AKS_AZURE_DEVOPS_SA_CACRT }}
        AKS_AZURE_DEVOPS_SA_TOKEN: ${{ variables.PROD01_AKS_AZURE_DEVOPS_SA_TOKEN }}
        AZURE_SERVICE_CONNECTION_PLAN_NAME: CSTAR-PROD-PLAN-SERVICE-CONN
        AZURE_SERVICE_CONNECTION_APPLY_NAME: PROD-CSTAR-SERVICE-CONN
