pr:
  autoCancel: true
  branches:
    include:
      - main
  paths:
    include:
      - "src/domains/idpay-app"
      - "src/domains/idpay-common"
    exclude:
      - '**/*.lock.hcl'
      - '**/*.md'

parameters:
  - name: 'DEV'
    displayName: 'Run on DEV environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'UAT'
    displayName: 'Run on UAT environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'PROD'
    displayName: 'Run on PROD environment'
    type: boolean
    default: True
    values:
      - False
      - True

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v6.9.0
      endpoint: "io-azure-devops-github-ro"

stages:
  #DEV
  - ${{ if eq(parameters['DEV'], true) }}:
    - template: './base-code-review-pipelines.yml'
      parameters:
        ENV: "dev"
        ENV_LOCATION: "weu"
        WORKING_DIR_APP: "src/domains/idpay-app"
        WORKING_DIR_COMMON: "src/domains/idpay-common"
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_DEV)'
        AKS_APISERVER_URL: '$(TF_DEV_AKS_APISERVER_URL)'
        AKS_AZURE_DEVOPS_SA_CACRT: '$(TF_DEV_AKS_AZURE_DEVOPS_SA_CACRT)'
        AKS_AZURE_DEVOPS_SA_TOKEN: '$(TF_DEV_AKS_AZURE_DEVOPS_SA_TOKEN)'
        AKS_NAME: '$(TF_AKS_DEV_NAME)'
        POOL_NAME: '$(TF_POOL_NAME_DEV)'
  #UAT
  - ${{ if eq(parameters['UAT'], true) }}:
    - template: './base-code-review-pipelines.yml'
      parameters:
        ENV: "uat"
        ENV_LOCATION: "weu"
        WORKING_DIR_APP: "src/domains/idpay-app"
        WORKING_DIR_COMMON: "src/domains/idpay-common"
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_UAT)'
        AKS_APISERVER_URL: '$(TF_UAT_AKS_APISERVER_URL)'
        AKS_AZURE_DEVOPS_SA_CACRT: '$(TF_UAT_AKS_AZURE_DEVOPS_SA_CACRT)'
        AKS_AZURE_DEVOPS_SA_TOKEN: '$(TF_UAT_AKS_AZURE_DEVOPS_SA_TOKEN)'
        AKS_NAME: '$(TF_AKS_UAT_NAME)'
        POOL_NAME: '$(TF_POOL_NAME_UAT)'
  #PROD
  - ${{ if eq(parameters['PROD'], true) }}:
    - template: './base-code-review-pipelines.yml'
      parameters:
        ENV: "prod"
        WORKING_DIR_APP: "src/domains/idpay-app"
        WORKING_DIR_COMMON: "src/domains/idpay-common"
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_PROD)'
        AKS_APISERVER_URL: '$(TF_PROD_AKS_APISERVER_URL)'
        AKS_AZURE_DEVOPS_SA_CACRT: '$(TF_PROD_AKS_AZURE_DEVOPS_SA_CACRT)'
        AKS_AZURE_DEVOPS_SA_TOKEN: '$(TF_PROD_AKS_AZURE_DEVOPS_SA_TOKEN)'
        AKS_NAME: '$(TF_AKS_PROD_NAME)'
        POOL_NAME: '$(TF_POOL_NAME_PROD)'
