# only manual
trigger: none
pr: none

parameters:
  - name: 'DEV'
    displayName: 'Run on DEV environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'UAT'
    displayName: 'Run on UAT environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'PROD'
    displayName: 'Run on PROD environment'
    type: boolean
    default: False
    values:
      - False
      - True

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v6.9.0
      endpoint: "io-azure-devops-github-ro"


stages:
  #DEV
  - ${{ if eq(parameters['DEV'], true) }}:
    - template: './base-deploy-pipelines.yml'
      parameters:
        ENV: 'dev'
        ENV_LOCATION: "weu"
        WORKING_DIR_MODULE: "src/packer"
        DOMAIN_NAME: 'packer'
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_DEV)'
        SC_APPLY_NAME: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_DEV)'
        POOL_NAME: '$(TF_POOL_NAME_DEV)'
  #UAT
  - ${{ if eq(parameters['UAT'], true) }}:
    - template: './base-deploy-pipelines.yml'
      parameters:
        ENV: 'uat'
        ENV_LOCATION: "weu"
        WORKING_DIR_MODULE: "src/packer"
        DOMAIN_NAME: 'packer'
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_UAT)'
        SC_APPLY_NAME: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_UAT)'
        POOL_NAME: '$(TF_POOL_NAME_UAT)'
  #PROD
  - ${{ if eq(parameters['PROD'], true) }}:
    - template: './base-deploy-pipelines.yml'
      parameters:
        ENV: 'prod'
        ENV_LOCATION: "weu"
        WORKING_DIR_MODULE: "src/packer"
        DOMAIN_NAME: 'packer'
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_PROD)'
        SC_APPLY_NAME: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_PROD)'
        POOL_NAME: '$(TF_POOL_NAME_PROD)'
