openapi: 3.0.1
info:
  title: IDPAY Email Notification Manager API
  description: IDPAY Email Notification Manager
  version: '1.0'
servers:
  - url: https://api-io.dev.cstar.pagopa.it/idpay/email-notification
tags:
- name: email-notification-manager
  description: Email Notification Manager operations
paths:
  /notify:
    post:
      tags:
        - email-notification-manager
      summary: Production of messages to be sent to one or more recipients for Institution and IDPAY Product basis.
      operationId: sendEmail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailMessageDTO'
      responses:
        "204":
          description: No Content
          content:
            application/json: {}
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  /users:
    get:
      tags:
        - email-notification-manager
      summary: Retrieve the institutional email of the user logged in to the Product for the relevant Institution.
      operationId: getInstitutionProductUserInfo
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInstitutionInfoDTO'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
components:
  schemas:
    ErrorDTO:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    UserInstitutionInfoDTO:
      type: object
      properties:
        email:
          type: string
    EmailMessageDTO:
      type: object
      properties:
        templateName:
          type: string
        subject:
          type: string
        senderEmail:
          type: string
        templateValues:
          type: object
          additionalProperties:
            type: string
        recipientEmail:
          type: string
        content:
          type: string
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
security:
  - Bearer: []