openapi: 3.0.1
info:
  title: RTD API to get AdE file
  description: RTD API to retrieve a deposited ADE file in SFTP by name
  version: '1.0'
servers:
  - url: ${host}
paths:
  /*:
    get:
      summary: GET BlobURI
      operationId: getBlob
      responses:
        "200":
          description: "Ok"
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
