openapi: 3.0.1
info:
  title: IDPAY-WelfarePortalUserPermissions_v1
  version: '1.0'
servers:
  - url: https://api-io.dev.cstar.pagopa.it/idpay/authorization
paths:
  /permissions:
    get:
      tags:
        - UserPermission
      summary: Return User Permissions
      operationId: userPermission
      responses:
        '200':
          description: Check successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPermissionDTO'
              example:
                role: string
                permissions:
                  - id: string
                    name: string
                    mode: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '404':
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
  "/consent":
    get:
      tags:
      - PortalConsent
      summary: Retrieve portal consent (ToS)
      operationId: getPortalConsent
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/PortalConsentDTO"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorDTO"
        '401':
          description: Authentication Failed
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorDTO"
        '429':
          description: Too Many Request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorDTO"
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorDTO"
    post:
      tags:
      - PortalConsent
      summary: Save portal consent
      operationId: savePortalConsent
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/PortalConsentDTO"
        required: true
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorDTO"
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorDTO"
        '429':
          description: Too Many Request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorDTO"
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorDTO"
components:
  schemas:
    UserPermissionDTO:
      title: UserPermissionDTO
      type: object
      properties:
        role:
          type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/PermissionDTO'
          description: List of permissions
    PermissionDTO:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        mode:
          type: string
    PortalConsentDTO:
      type: object
      properties:
        versionId:
          type: string
        firstAcceptance:
          type: boolean
    ErrorDTO:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
security:
  - Bearer: []
tags:
  - name: UserPermission
    description: ''
