openapi: 3.0.1
info:
  title: FA IO Merchant Api
  description: Api and Models
  version: "1.0"
servers:
  - url: https://${host}/fa/io/merchant
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
tags:
  - name: Fatturazione Automatica Merchant Controller
    description: Fa Merchant Controller Impl
paths:
  /shop/{shopId}:
    get:
      tags:
        - Fatturazione Automatica Merchant Controller
      summary: Get merchant by shop id
      description: GET Merchant details
      operationId: getMerchantByShopId
      parameters:
        - name: shopId
          in: path
          description: Shop id
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MerchantResource'
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
  /:
    put:
      tags:
        - Fatturazione Automatica Merchant Controller
      summary: onboardingMerchantByIO
      description: onboardingMerchantByIO
      operationId: onboardingMerchantByIOUsingPut
      requestBody:
        description: Merchant body
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Merchant'
        required: false
      responses:
        200:
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/MerchantResource'
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
      x-codegen-request-body-name: Merchant
components:
  schemas:
    Merchant:
      title: Merchant
      type: object
      properties:
        vatNumber:
          type: string
          example: "12345678910"
        companyName:
          type: string
          example: companyName
        registerCode:
          type: string
          example: "12345"
        registerAuth:
          type: string
          example: aaa123aaa123
        shops:
          type: array
          items:
            $ref: '#/components/schemas/MerchantShop'
    MerchantShop:
      title: MerchantShop
      type: object
      properties:
        callId:
          type: integer
          example: 1
        companyName:
          type: string
          example: companyName
        companyAddress:
          type: string
          example: via Roma 1
        providerId:
          type: integer
          example: 1
        contactName:
          type: string
          example: Mario
        contactSurname:
          type: string
          example: Rossi
        contactEmail:
          type: string
          example: email@email.it
        contactTel1:
          type: string
          example: +3932012345612
    MerchantResource:
      title: MerchantResource
      type: object
      properties:
        vatNumber:
          type: string
        cancellationTimestampTC:
          type: string
          format: date-time
        status:
          type: string
        companyName:
          type: string
        companyAddress:
          type: string
        enabled:
          type: boolean
        timestampTC:
          type: string
          format: date-time
        shops:
          type: array
          items:
            $ref: '#/components/schemas/Shops'
    MerchantShopResource:
      title: MerchantShopResource
      type: object
      properties:
        callId:
          type: integer
          example: 1
        contractId:
          type: integer
          example: 1
        shopId:
          type: string
          example: 2020_12345678910_0000001
    Shops:
      title: Shops
      type: object
      properties:
        merchantId:
          type: string
        contracts:
          type: array
          items:
            $ref: '#/components/schemas/MerchantShopContractResource'
    MerchantShopContractResource:
      title: MerchantShopResource
      type: object
      properties:
        contractId:
          type: integer
          example: 1
        shopId:
          type: string
        activation:
          type: string
          format: date-time
        enabled:
          type: boolean
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
