CREATE ROLE "MONITORING_PDND_USER";
ALTER ROLE "MONITORING_PDND_USER" WITH INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION;
ALTER USER "MONITORING_PDND_USER" WITH PASSWORD '${monitoringPdndUserPassword}';
GRANT CREATE ON DATABASE fa TO "MONITORING_PDND_USER";
GRANT CONNECT ON DATABASE postgres TO "MONITORING_PDND_USER";