CREATE ROLE "MONITORING_SIA_USER";
ALTER ROLE "MONITORING_SIA_USER" WITH INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION;
ALTER USER "MONITORING_SIA_USER" WITH PASSWORD '${monitoringSiaUserPassword}';
GRANT CREATE ON DATABASE fa TO "MONITORING_SIA_USER";
GRANT CONNECT ON DATABASE postgres TO "MONITORING_SIA_USER";
