CREATE ROLE "MONITORING_OPERATION_USER";
ALTER ROLE "MONITORING_OPERATION_USER" WITH INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION;
ALTER USER "MONITORING_OPERATION_USER" WITH PASSWORD '${monitoringOperationUserPassword}';
GRANT CREATE ON DATABASE fa TO "MONITORING_OPERATION_USER";
GRANT CONNECT ON DATABASE postgres TO "MONITORING_OPERATION_USER";
