openapi: 3.0.1
info:
  title: RTD API to put AdE ACK file
  description: RTD API to deposit a synthetic ADE ACK file in SFTP
  version: '1.0'
servers:
  - url: ${host}
paths:
  /*:
    put:
      summary: PUT BlobURI
      operationId: putBlob
      responses:
        "200":
          description: "Ok"
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: []
  - apiKeyQuery: []
