openapi: 3.0.0
info:
  title: FA Proxy
  version: "1.0"
  description: proxy to IO call bypassing CORS
security:
  - Bearer: []
paths:
  /pp-restapi-CD/v2/wallet:
    get:
      description: Get Wallet
      operationId: getWallet
      summary: Get Wallet
      responses:
        "200":
          description: OK

  /io/session:
    get:
      description: Get IO sessions tokens
      operationId: getIoSession
      summary: Get IO sessions tokens
      responses:
        "200":
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: "#/components/schemas/IOSessions"
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
servers:
  - url: https://${host}/
    variables:
      host:
        default: unknown
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
      description: Token IO
  schemas:
    IOSessions:
      type: object
      properties:
        bpdToken:
          type: string
        fimsToken:
          type: string
        myPortalToken:
          type: string
        spidLevel:
          type: string
        walletToken:
          type: string
        zendeskToken:
          type: string
