openapi: 3.0.3
info:
  title: Payment Instrument - OpenAPI 3.0
  description: |-
    Payment Instrument APIs 
  termsOfService: http://pagopa.it/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost:8080
tags:
  - name: PaymentInstrument
paths:
  /{paymentInstrumentId}:
    delete:
      tags:
        - PaymentInstrument
      summary: Called by wallet to delete a payment instrument 
      description: Called by wallet to delete a payment instrument 
      operationId: paymentInstrumentDelete
      parameters:
        - name: paymentInstrumentId 
          in: path
          description: The payment instrument ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '404':
          description: The requested ID was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '429':
          description: Too many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
        '500':
          description: Server ERROR
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDTO'
components:
  schemas:
    ErrorDTO:
      type: object
      properties:
        code:
          type: string
        message:
          type: string